name: CircleSquareArchitects/Project Experience
favicon: null
layout_spectrum: 0.6288152541965246
typography_spectrum: 0.3379794030915946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#53524d'
    - '#aad3c1'
    - '#baac00'
  brandStrength: 0.5
  lightness: 0.7344670942984521
  saturation: 0.14287488674744964
  rhythmicContrast: 0.25
purpose: []
